version: "3"
services:

  hub:
    image: selenium/hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SCREEN_HEIGHT=1600
      - SCREEN_WIDTH=2560
      - IONIC_SNAPSHOT_KEY

  e2e-server:
    image: nginx
    volumes:
      - ../../../core:/usr/share/nginx/html
